# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efb6c9fcb3c41724eaeb2ae693c63935fe04fe130f77f1cb461f27c635ada61087027290484c6531707fb0a9518448ccb9727d73e2a4a85dcc691ea18ee446a9

test:
  secret_key_base: 0616899c6c98741934f6dbee735a0e83f879ce4448f329e7be15a2914d94145cdd494699d3845a9120878a3cbbbd2c05671941e5b60c1c2f227c77977b030de8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
